apiVersion: v1
kind: Service
metadata:
  name: spotifybuddies-redis
  namespace: spotifybuddies-monitoring
spec:
  type: ClusterIP
  selector:
    app: spotifybuddies-redis
  ports:
    - port: 6379
      targetPort: redis
      name: redis
