name: persist_block
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    expose:
      - "9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "your-access-key"
      MINIO_ROOT_PASSWORD: "your-secret-key"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    volumes:
      - /mnt/block/minio_data:/data
    networks:
      - production_net

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      # POSTGRES_MULTIPLE_DATABASES: mlflowdb,client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: client
    ports:
      - "5432:5432"
    volumes:
      - /mnt/block/postgres_data:/var/lib/postgresql/data
        #- ../docker:/docker-entrypoint-initdb.d
    networks:
      - production_net
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  metabase:
    image: metabase/metabase:v0.45.0
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "client"      # Replace with your database name
      MB_DB_PORT: "5432"        # Replace with your Postgres port
      MB_DB_USER: "postgres"        # Replace with your Postgres username
      MB_DB_PASS: "1234"    # Replace with your Postgres password
      MB_DB_HOST: "postgres"        # Replace with your Postgres host (e.g., localhost or IP)
    restart: always
    networks:
        - production_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  production_net:
    external: true