services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379

  fastapi_server:
    build:
      context: ../model_server/
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:80"
    expose:
      - "8000"
    environment:
      - DEBUG=False
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
