apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: spotifybuddies-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: webserver
          image: apache/airflow:2.8.0
          command: ["airflow", "webserver"]
          envFrom:
            - configMapRef:
                name: airflow-config
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: spotifybuddies-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.8.0
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: spotifybuddies-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: apache/airflow:2.8.0
          command: ["airflow", "celery", "worker"]
          envFrom:
            - configMapRef:
                name: airflow-config
