apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: spotifybuddies-monitoring
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
