apiVersion: v1
kind: Service
metadata:
  name: spotifybuddies-fastapi
  namespace: spotifybuddies-platform
spec:
  type: NodePort
  selector:
    app: spotifybuddies-fastapi
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001
      name: http
