apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: compose-build-
spec:
  entrypoint: build-flow

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: compose-build
          template: compose-build

  - name: git-clone
    dnsPolicy: "None"
    dnsConfig:
      nameservers: [8.8.8.8, 1.1.1.1]
    container:
      image: alpine/git
      command: [sh, -c]
      args: |
        mkdir -p /mnt/workspace \
        && for i in 1 2 3 4 5; do
             echo "Clone attempt $i" ;
             git clone --depth 1 https://github.com/AguLeon/MLOps_G47_SpotifyBuddies.git /mnt/workspace && break ;
             sleep 5 ;
           done ;
        [ -d /mnt/workspace/.git ] || { echo "Clone failed"; exit 1; }
      volumeMounts:
        - name: workdir
          mountPath: /mnt/workspace

  - name: compose-build
    sidecars:
      - name: dind
        image: docker:24-dind
        securityContext:
          privileged: true
        args: ["--insecure-registry=registry.kube-system.svc.cluster.local:5000"]
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace
    container:
      name: main
      image: docker:24-cli
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      workingDir: /mnt/workspace
      command: ["sh", "-c"]
      args: |
        chmod +x docker/run_docker_compose.sh &&
        docker/run_docker_compose.sh --push \
          --registry registry.kube-system.svc.cluster.local:5000
      volumeMounts:
        - name: workdir
          mountPath: /mnt/workspace