apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-pvc-build-
spec:
  entrypoint: kaniko-build-flow
  hostNetwork: true
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: kaniko-build-flow
    steps:
    - - name: clone-repo
        template: git-clone
      - name: kaniko-build
        template: kaniko

  - name: git-clone
    hostNetwork: true
    dnsPolicy: None
    dnsConfig:
      nameservers:
        - 8.8.8.8
        - 1.1.1.1
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          set -ex
          mkdir -p /mnt/workspace
          MAX_RETRIES=5
          i=1
          while [ $i -le $MAX_RETRIES ]; do
            git clone https://github.com/AguLeon/MLOps_G47_SpotifyBuddies.git /mnt/workspace && break
            i=$((i+1))
            sleep 5
          done
          ls -la /mnt/workspace
    volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    hostNetwork: true
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.kube-system.svc.cluster.local:5000/spotifybuddies-app:staging-1.0.0
        - --destination=registry.kube-system.svc.cluster.local:5000/spotifybuddies-app:canary-1.0.0
        - --destination=registry.kube-system.svc.cluster.local:5000/spotifybuddies-app:production-1.0.0
        - --insecure
        - --insecure-pull
        - --skip-tls-verify-pull
    volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace
